
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL").gsub("?", "_development?") %>

test:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL").gsub("?", "_test?") %>

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    encoding: utf8
  cache:
    <<: *primary_production
    database: database_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: database_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: database_production_cable
    migrations_paths: db/cable_migrate
