default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: innercircle_development
  username: postgres
  password:
  host: localhost

test:
  <<: *default
  database: innercircle_test
  username: postgres
  password:
  host: localhost

production:
  <<: *default
  url: <%= ENV["DATABASE_URL_POSTGRESQL"] %>
  sslmode: require
