default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: innercircle_development

test:
  <<: *default
  database: innercircle_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  pool: 5
  timeout: 5000
